version: '3.3'
services:
  dynamo:
    image: amazon/dynamodb-local:latest
    hostname: dynamo
    container_name: dynamo
    ports:
      - "8000:8000"
    networks:
      - atdd-network
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath .